### ISSUE TITLE
Finalize NAME for the project

### ISSUE THREAD

**Issue by halfalpine** [EricSchles/fact_checker_website#10]
Here's a brainstorm list of ideas for naming the project. 

The central idea is that this project is differentiated by the fact that many people are involved, that it is of and from the people, and that it is transparent. More suggestions/refinements are welcome, of course!

wikinews
we the people
thousand eyes
all eyes
eyes together
pennies
haystack
newsdrops
clearnews
daylight
openlight
transparency
transparentize
clear air
clear.ly
open air
ournews
wikinews
crowdpaper
crowdnews
checked-news
fake news tracker
realnews
alltheeyes
open news

AUTHORITY
Verify
Veritas
Truth
Actual
Real
Final

THE PEOPLE
All
Omni
Wiki
Crowd
Public good
Group
Our(ournews)

**Comment by joshhersh** [comment]
Other name ideas:

Fix the News Tracker
Fake News Hub
Fake News Shop
The Citizen Fact-Checker
Citizen’s Fact Checker
Check The News
Uncover Fake News
Truth in News

**Comment by EricSchles** [comment]
Critical-Think
